Repository checkmarble/marble-backend, pull requests merged in 2025-04, with the labels that each got.

#947 Detail the structure of the backend in the README.
  README.md
Labels: documentation, enhancement

#951 Add whitelist permissions to VIEWER role.
  models/role_permission.go
Labels: bug, go

#959 Change related cases endpoint to accept pivot.
  api/handle_cases.go
  api/routes.go
  repositories/case_repository.go
  usecases/case_usecase.go
Labels: enhancement, go

#960 Added various case events.
  models/case_event.go
  usecases/case_usecase.go
  usecases/suspicious_activity_report_usecase.go
Labels: enhancement, go

#962 Implemented case escalation.
  api/handle_cases.go
  api/handle_inboxes.go
  api/routes.go
  dto/inbox_dto.go
  mocks/enforce_security.go
  mocks/inboxes_repository.go
  models/case_event.go
  models/inbox.go
  repositories/case_repository.go
  repositories/dbmodels/db_inbox.go
  repositories/inboxes_repository.go
  repositories/migrations/20250416151100_add_inbox_escalation.sql
  usecases/case_usecase.go
  usecases/inboxes/inboxes.go
  usecases/inboxes_usecase.go
  usecases/security/enforce_security_inboxes.go
Labels: enhancement, go

#971 fix: fuzzy match filter
  repositories/migrations/20250424120000_add_fuzzystrmatch_extension.sql
Labels: bug

#970 Remove required constraint on comment when reviewing decision.
  dto/case_dto.go
Labels: enhancement, go

#976 Add logs to infra checks for OpenSanctions.
  repositories/opensanctions_repository.go
Labels: enhancement, go

#977 Change Yente healthcheck to /readyz
  repositories/opensanctions_repository.go
Labels: bug, go

#974 Self-assign case on various events.
  usecases/case_usecase.go
  usecases/suspicious_activity_report_usecase.go
Labels: enhancement, go
