Repository checkmarble/marble-backend, pull requests merged in 2025-03, with the labels that each got.

#880 Change index cleanup interval to run every hour.
  usecases/scheduled_execution/index_cleanup_job.go
Labels: bug, go

#881 Fixed bug where all test runs would set as summarized.
  repositories/scenario_testrun.go
Labels: bug, go

#878 Add NER API authorization.
  cmd/server.go
  cmd/worker.go
  infra/opensanctions.go
  repositories/name_recognition_repository.go
  repositories/name_recognition_repository_test.go
  usecases/evaluate_scenario/evaluate_sanction_check.go
Labels: enhancement, go

#893 tentative fix: decisions by outcome stats are wrong due to missing filter
  repositories/decisions_repository.go
  usecases/decision_usecase.go
  usecases/scheduled_execution/test_run_summary_job.go
Labels: bug

#899 Fixed index creation when index names were too long.
  usecases/scheduled_execution/index_creation_job.go
Labels: bug, go

#900 API endpoints for case assigment.
  api/handle_cases.go
  api/routes.go
  dto/case_dto.go
  models/case.go
  repositories/case_repository.go
  repositories/dbmodels/db_case.go
  repositories/migrations/20250310143900_create_case_assignment.sql
  usecases/case_usecase.go
  usecases/security/enforce_security_case.go
  usecases/usecases_with_creds.go
Labels: enhancement, go

#909 Better ingestion errors
  usecases/ingestion_usecase.go
Labels: enhancement, go

#910 Handle timezone-less RFC3339 datetimes
  usecases/ingestion_usecase.go
  usecases/ingestion_usecase_test.go
  usecases/payload_parser/payload.go
  usecases/payload_parser/payload_test.go
Labels: enhancement, go

#913 Add ingestion special case error messages.
  usecases/ingestion_usecase.go
Labels: enhancement, go

#927 Fix memory leak in match enrichment
  repositories/name_recognition_repository.go
  repositories/opensanctions_repository.go
  usecases/scheduled_execution/index_creation_job.go
  usecases/scheduled_execution/match_enrichment_job.go
  usecases/usecases_with_creds.go
Labels: bug, go

#918 chore(doc): Improve getting started section
  README.md
  mise.toml
Labels: documentation

#933 Remove duplicated operation ID and formatting.
  specs/v1_public_api.yaml
Labels: bug, go

#935 Rename sanction checks in public API to transaction screening.
  pubapi/tests/specs/v1/sanction_checks.go
  pubapi/tests/specs/v1/whitelists.go
  pubapi/v1/routes.go
  pubapi/v1/sanction_checks.go
  specs/v1_public_api.yaml
Labels: enhancement, go

#936 Upgrade to golangci-lint v2
  .github/workflows/backend_test_workflow.yaml
  .golangci.yml
Labels: enhancement, go

#916 Handle null index_version for OpenSanctions datasets.
  api/handle_sanction_checks.go
  dto/sanction_check_dataset_dto.go
  models/opensanctions.go
  repositories/httpmodels/http_opensanctions_dataset_freshness.go
  repositories/opensanctions_repository.go
Labels: bug, go

#941 Add migrations_run boolean to signup status.
  api/handle_signup_status.go
  usecases/signup_usecase.go
Labels: enhancement, go
