Repository checkmarble/marble-backend, pull requests merged in 2025-08, with the labels that each got.

#1109 Handle no rows returned for next assignable user.
  repositories/auto_assignment_repository.go
Labels: bug, go

#1110 Take into account assignable users when fetching assignable cases.
  repositories/auto_assignment_repository.go
Labels: bug, go

#1112 Fix query for assignable cases.
  repositories/auto_assignment_repository.go
Labels: bug, go

#1113 Order oldest case first for auto assignment.
  repositories/auto_assignment_repository.go
Labels: bug, go

#1118 feat(metrics_collection): add AI case review metrics collector and database migration for indexing
  repositories/case_review_repository.go
  repositories/migrations/20250808122214_add_index_created_at_ai_case_review.sql
  usecases/metrics_collection/ai_case_review_collector.go
  usecases/metrics_collection/collector.go
  usecases/metrics_collection/collector_test.go
  usecases/metrics_collection/constant.go
Labels: enhancement, go

#1108 feat(case_review): enhance CaseReviewV1 with proofs
  api/handle_cases.go
  api/routes.go
  dto/agent_dto/case.go
  dto/agent_dto/case_review.go
  dto/agent_dto/decisions.go
  models/ai_case_review.go
  repositories/case_review_repository.go
  repositories/dbmodels/db_ai_case_review.go
  usecases/ai_agent/ai_agent_usecase.go
  usecases/ai_agent/async_case_review.go
Labels: enhancement, go

#1124 Accept an array of UUID in workflow rule_hit condition.
  dto/workflows.go
  usecases/decision_workflows/conditions.go
  usecases/workflows_test.go
Labels: bug, go

#1130 feat(migrations): add migration to set file_temp_reference as NOT NULL
  repositories/migrations/20250820142413_alter_temp_file_ref_non_null.sql
Labels: bug

#1133 feat(worker): add worker monitor service based on river UI
  docker-compose.yml
Labels: enhancement, dependencies

#1129 fix(ai_case_review): update objectTables check to ensure non-empty slice before processing
  usecases/ai_agent/ai_agent_usecase.go
Labels: bug, go

#1144 Be explicit about OpenSanctions match request content-type.
  repositories/opensanctions_repository.go
Labels: bug, enhancement, go

#1152 Fixed memory leak caused by defer retaining writers.
  usecases/scheduled_execution/offloading_job.go
Labels: bug, go

#1153 fix(openapi v1): fix return type from ErrorDto to Error
  dto/openapi.go
Labels: bug, go
