Repository checkmarble/marble-backend, pull requests merged in 2025-10, with the labels that each got.

#1227 Invert single and double quotes for interpolation.
  Dockerfile
Labels: bug

#1214 Make Firebase API key required.
  cmd/server.go
Labels: go, refactor

#1229 Add audit trail events on workflow edition.
  repositories/migrations/20251001151300_add_workflow_audit_trail.sql
Labels: enhancement, go

#1230 fix: add missing field in public openapi
  pubapi/openapi/v1.yml
Labels: bug

#1224 Implement analytics settings endpoints.
  api/handle_datamodel_exported_fields.go
  api/routes.go
  dto/analytics_settings.go
  repositories/analytics_settings.go
  repositories/dbmodels/db_analytics_settings.go
  usecases/analytics_settings.go
  usecases/usecases_with_creds.go
Labels: enhancement, go

#1236 feat(ai_agent): add endpoint to describe AST in body
  api/handle_scenario_iterations.go
  api/routes.go
  dto/rule_dto.go
  usecases/ai_agent/ai_agent_usecase.go
  usecases/ai_agent/ai_rule_assist.go
  usecases/usecases_with_creds.go
Labels: enhancement, go

#1238 Abort if OIDC is set up without SSO license entitlement
  cmd/server.go
Labels: enhancement, go

#1239 Upgrade gocloud to 0.43.0.
  go.mod
  go.sum
  infra/analytics.go
  repositories/blob_repository.go
  usecases/executor_factory/analytics_executor_factory.go
Labels: dependencies, go
